# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utility_protobuf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16utility_protobuf.proto\x12\x10utility_protobuf\"8\n\x0eInitReqMessage\x12\x18\n\x10\x65xpire_timestamp\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\"!\n\x0fInitRespMessage\x12\x0e\n\x06status\x18\x01 \x01(\x05\"x\n\x17ResampleImageReqMessage\x12\x12\n\ndecode_pic\x18\x01 \x01(\t\x12\x12\n\nencode_pic\x18\x02 \x01(\t\x12\x10\n\x08re_pic_x\x18\x03 \x01(\x05\x12\x10\n\x08re_pic_y\x18\x04 \x01(\x05\x12\x11\n\tunknown_0\x18\x05 \x01(\x05\",\n\x18ResampleImageRespMessage\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\"m\n\x0fTextScanMessage\x12\x14\n\x0ctext_scan_id\x18\x01 \x01(\x05\x12\x10\n\x08pic_path\x18\x02 \x01(\t\x12\x11\n\thave_text\x18\x03 \x01(\x05\x12\x11\n\tunknown_0\x18\x04 \x01(\x05\x12\x0c\n\x04rate\x18\x05 \x01(\x02\"\xce\x01\n\x10QRScanReqMessage\x12\x12\n\norigin_pic\x18\x01 \x01(\t\x12\x12\n\ndecode_pic\x18\x02 \x01(\t\x12\x11\n\tunknown_0\x18\x03 \x01(\x05\x12\x17\n\x0f\x65ncode_pic_data\x18\x04 \x01(\x0c\x12\x14\n\x0c\x65ncode_pic_x\x18\x05 \x01(\x05\x12\x14\n\x0c\x65ncode_pic_y\x18\x06 \x01(\x05\x12\x11\n\tunknown_1\x18\x07 \x01(\x05\x12\x14\n\x0ctext_scan_id\x18\x08 \x01(\x05\x12\x11\n\tunknown_3\x18\t \x01(\x05\"\xd6\x01\n\x11QRScanRespMessage\x12\x43\n\tqr_result\x18\x01 \x03(\x0b\x32\x30.utility_protobuf.QRScanRespMessage.QRScanResult\x12\x11\n\tunknown_0\x18\x02 \x01(\x05\x1ai\n\x0cQRScanResult\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x12\x10\n\x08unknow_0\x18\x02 \x01(\x05\x12\x11\n\tunknown_1\x18\x03 \x01(\x01\x12\x11\n\tunknown_2\x18\x04 \x01(\x01\x12\x11\n\tunknown_3\x18\x05 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utility_protobuf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITREQMESSAGE._serialized_start=44
  _INITREQMESSAGE._serialized_end=100
  _INITRESPMESSAGE._serialized_start=102
  _INITRESPMESSAGE._serialized_end=135
  _RESAMPLEIMAGEREQMESSAGE._serialized_start=137
  _RESAMPLEIMAGEREQMESSAGE._serialized_end=257
  _RESAMPLEIMAGERESPMESSAGE._serialized_start=259
  _RESAMPLEIMAGERESPMESSAGE._serialized_end=303
  _TEXTSCANMESSAGE._serialized_start=305
  _TEXTSCANMESSAGE._serialized_end=414
  _QRSCANREQMESSAGE._serialized_start=417
  _QRSCANREQMESSAGE._serialized_end=623
  _QRSCANRESPMESSAGE._serialized_start=626
  _QRSCANRESPMESSAGE._serialized_end=840
  _QRSCANRESPMESSAGE_QRSCANRESULT._serialized_start=735
  _QRSCANRESPMESSAGE_QRSCANRESULT._serialized_end=840
# @@protoc_insertion_point(module_scope)
